image: node:8.11 # can be upgraded, depending on your node version used

stages:
- test
- build

test:
  stage: test
  script:
  - npm install
  - npm run build
  - npm test -- --coverage
  only:
  - dev # or dev, the branch you want to publish

build:
  stage: build
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public # mandatory, other folder won't work
  only:
  - dev # or dev, the branch you want to publish