language: node_js
node_js:
  - 11.13

cache:
  yarn: true

before_install:
  - sudo apt-get install -y libsecret-1-dev

install:
  # use the new "ci" command for fastest installs on CI
  - cp src/config.sample.js src/config.js
  - yarn
  - yarn build

stages:
  - unit_test
#  - test

jobs:
  include:
    - stage: unit_test
      name: "Unit Tests"
      script:
        - npm --version
        # - npm test -- --coverage
      after_script:
        #
        # Code climate configuration
        #
        - npm install -g codeclimate-test-reporter
        - codeclimate-test-reporter < coverage/lcov.info
