language: node_js
git:
  submodules: false
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- --coverage
after_script:
  #
  # Code climate configuration
  #
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info